### ISSUE TITLE
Project still active?

### ISSUE THREAD

**Issue by jasdeepsingh** [ianwhite/pickle#68]
Thinking of using `pickle` for a project, Just wondering if it's still being actively maintained or there's another fork that is?

**Comment by chewi** [comment]
From what I said in #67 the other day:

I'm not aware of a replacement. I gave it a good shot in the arm a while back but that ended up going beyond what I needed for my day job and I have plenty of more interesting open source responsibilities elsewhere. We still use it and it still works, surprisingly enough. I suppose it doesn't get a lot of attention because the approach is generally frowned upon by the Cucumber community.

**Comment by jasdeepsingh** [comment]
That answers my question. Thanks. closing.
